### ISSUE TITLE
APIException: geometry not found in JSON

### ISSUE THREAD

**Issue by basildane** [adimarov/weather-gov-wrapper#1]
Hi, I'm trying to call AlertsActive.
I've tried many different parameter combinations, but I always get a 500: geometry not found in JSON.

```
var api = new DefaultApi("https://api.weather.gov");
var zone = new List<string>
{
    "MDZ014"
};

var result = api.AlertsActive(zone: zone);

```
Any hints?

**Comment by adimarov** [comment]
Hello @basildane, seems to be a type mismatch.
https://github.com/adimarov/weather-gov-wrapper/pull/2
PR has been merged.

**Comment by basildane** [comment]
Thank you, I will test it soon.
